### ISSUE TITLE
Ads, telemetry, and hjem premium

### ISSUE THREAD

**Issue by deviantsemicolon** [feel-co/hjem#8]
![ResizedImage_2024-12-27_18-53-56_4637](https://github.com/user-attachments/assets/22a9e0fc-3673-4038-9d99-42a22abf5b0f)

As per the maintainer's wishes(shown above), this issue is meant to begin the process of adding advertisements, telemetry, and hjem premium to the repo.

**Comment by deviantsemicolon** [comment]
(This is a joke btw plz don't sue me raf 🥺)

**Comment by eclairevoyant** [comment]
Thanks, we'll consider this one in the year 3000.

**Comment by deviantsemicolon** [comment]
> Thanks, we'll consider this one in the year 3000.

An excellent business decision 🥂
